Repository se-gam/segam-web, pull requests merged in 2024-03, with the labels that each got.

#99 [#98] fix: 메인 배포 전 QA 이슈 수정
  public/images/segam.png
  src/app/check/route.tsx
  src/app/stack/credit/page.tsx
  src/components/common/icons/icons.tsx
  src/components/common/navLinks/NavLinks.tsx
  src/components/studyroom/list/studyRoomSlotItem.tsx
Labels: QA

#102 [#84] fix: 스터디룸 액션 로딩 상태 추가
  src/components/common/button/button.tsx
  src/components/dashboard/card/studyRoomCard.tsx
  src/components/studyroom/list/studyRoomReservationItem.tsx
  src/components/studyroom/list/studyRoomSlotItem.tsx
  src/components/studyroom/reservationForm.tsx
Labels: QA

#109 [QA-REAL] QA-REAL 긴급 수정 후 메인 머지
  src/app/(root)/dashboard/(overview)/layout.tsx
  src/app/(root)/dashboard/(overview)/page.tsx
  src/components/dashboard/card/studyRoomCard.tsx
  src/hooks/useModal.tsx
Labels: QA

#110 Fix/qa real 106
  src/components/dashboard/card/studyRoomCard.tsx
  src/components/mypage/menuList.tsx
  src/components/studyroom/list/studyRoomReservationItem.tsx
  src/components/studyroom/list/studyRoomReservationList.tsx
  src/components/studyroom/reservation/addFriendModal.tsx
  src/components/studyroom/reservation/checkUser.tsx
  src/components/studyroom/reservationForm.tsx
  src/lib/actions/auth.ts
  src/lib/actions/studyroom.ts
  src/lib/actions/user.ts
  src/middleware.ts
Labels: QA

#112 [#105] fix: isLeader 분기 따라 버튼 활성화
  src/components/studyroom/list/studyRoomReservationItem.tsx
  src/components/studyroom/list/studyRoomReservationList.tsx
Labels: QA

#116 로그인 오류 수정으로 인한 메인 머지
  src/components/studyroom/list/studyRoomReservationItem.tsx
  src/components/studyroom/list/studyRoomReservationList.tsx
  src/utils/fetchExtended.ts
Labels: bug

#120 [#119] fix: 캐시관련 로직 수정
  src/app/(root)/dashboard/(overview)/layout.tsx
  src/app/(root)/dashboard/(overview)/page.tsx
  src/app/(root)/dashboard/attendance/layout.tsx
  src/app/(root)/dashboard/layout.tsx
  src/app/(root)/dashboard/studyroom/page.tsx
  src/app/(root)/loading.tsx
  src/app/check/route.ts
  src/app/login/page.tsx
  src/app/stack/credit/page.tsx
  src/components/studyroom/StudyRoomModalButton.tsx
  src/components/studyroom/list/studyRoomFilterModal.tsx
  src/components/studyroom/list/studyRoomSlotItem.tsx
  src/components/studyroom/list/studyRoomSlotList.tsx
  src/components/studyroom/reservationForm.tsx
  src/components/studyroom/reservationView.tsx
  src/components/studyroom/studyRoomView.tsx
  src/lib/actions/attendance.ts
  src/lib/actions/auth.ts
  src/lib/actions/studyroom.ts
  src/lib/definitions.ts
  src/middleware.ts
Labels: bug

#121 캐시관련 로직 수정 후 메인 머지
  src/app/(root)/dashboard/(overview)/layout.tsx
  src/app/(root)/dashboard/(overview)/page.tsx
  src/app/(root)/dashboard/attendance/layout.tsx
  src/app/(root)/dashboard/layout.tsx
  src/app/(root)/dashboard/studyroom/page.tsx
  src/app/(root)/loading.tsx
  src/app/check/route.ts
  src/app/login/page.tsx
  src/app/stack/credit/page.tsx
  src/components/studyroom/StudyRoomModalButton.tsx
  src/components/studyroom/list/studyRoomFilterModal.tsx
  src/components/studyroom/list/studyRoomSlotItem.tsx
  src/components/studyroom/list/studyRoomSlotList.tsx
  src/components/studyroom/reservationForm.tsx
  src/components/studyroom/reservationView.tsx
  src/components/studyroom/studyRoomView.tsx
  src/lib/actions/attendance.ts
  src/lib/actions/auth.ts
  src/lib/actions/studyroom.ts
  src/lib/definitions.ts
  src/middleware.ts
Labels: bug

#123 [#122] fix: studyroom slot 날짜 설정 오류 해결
  src/components/studyroom/list/studyRoomSlotItem.tsx
Labels: bug

#126 [#125] feat: 개인정보 처리방침 추가
  src/app/login/page.tsx
  src/app/stack/privacy/page.tsx
Labels: 온보드

#129 [#128] remove: 세종대 타이틀 제거
  src/app/login/page.tsx
Labels: 배포

#132 [#131] fix: 출석 세부페이지 스크롤 이슈 해결
  src/app/stack/attendance/[id]/page.tsx
Labels: bug

#133 출석 세부페이지 스크롤 오류 해결로 인한 머지
  src/app/stack/attendance/[id]/page.tsx
Labels: bug

#135 [#134] feat: api오류 디스코드 훅 추가
  src/lib/actions/attendance.ts
  src/lib/actions/discord.ts
  src/lib/actions/studyroom.ts
  src/utils/fetchExtended.ts
Labels: 배포
