Repository se-gam/segam-web, pull requests merged in 2024-04, with the labels that each got.

#142 [#141] fix: 스터디룸 리스트 정렬화
  src/components/studyroom/studyRoomView.tsx
Labels: bug, 스터디룸

#147 Fix/timezone error 146
  src/utils/calAnnounceData.ts
Labels: bug

#154 SL 대응에 따른 메인 배포
  public/images/SL.png
  src/components/common/icons/icons.tsx
  src/components/studyroom/list/studyRoomSlotItem.tsx
  src/utils/calReservationData.ts
Labels: 비정기배포
